name: CI

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - CHANGELOG.md
    - LICENSE.md
    - README.md

  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - CHANGELOG.md
    - LICENSE.md
    - README.md

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Lint sources
      run: npm run lint
